os: windows
language: shell

install: 
  - choco install python3 --version 3.7.4
  - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
  
before_script:
  - py -m pip install pyinstaller
  
script:
  - echo Hello
  - pyinstaller --onefile il2-kills.py
  - cd dist
  - dir
  
