os: windows
language: shell

install: 
  - choco install python3
  
before_script:
  - py -m pip install --user pyinstaller
  
script:
  - echo Hello
  - py -m pyinstaller --onefile il2-kills.py
  - cd dist
  - dir
  
