os: windows
language: shell

install: 
  - choco install python3 --version 3.7.4
  - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
  
before_script:
  - py -m pip install requests
  
script:
  - py il2-kills.py -h

before_deploy:
  - py -m pip install pyinstaller
  - pyinstaller --onefile il2-kills.py
  - export DIST_NAME="il2-kills_$TRAVIS_TAG"
  - mkdir "dist/$DIST_NAME"
  - cp ./LICENSE "dist/$DIST_NAME/"
  - cp ./README.md "dist/$DIST_NAME/"
  - cp ./README.md "dist/$DIST_NAME/README.txt"
  - cd dist
  - ./il2-kills.exe -h
  - cp ./il2-kills.exe "$DIST_NAME"
  - 7z a "../$DIST_NAME.zip" "$DIST_NAME/"

deploy:
  provider: releases
  api_key:
    secure: "$GH_DEPLOY_KEY"
  file: "$DIST_NAME.zip"
  skip_cleanup: true
  draft: true
  on:
    tags: true
