os: windows
language: shell

install: 
  - choco install python3 --version 3.7.4
  - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
  
before_script:
  - py -m pip install requests pyinstaller
  
script:
  - pyinstaller --onefile il2-kills.py
  - cp LICENSE dist/
  - cp README.md dist/
  - cd dist
  - cp README.md README.txt
  - ./il2-kills.exe -h
